### ISSUE TITLE
Incorrect calculation of RP ID

### ISSUE THREAD

**Issue by rogerta** [Devolutions/slauth#59]
I believe there may be a problem with the calculation of the default RP ID in `CredentialCreationVerifier::verify` when one  is not explicitly specified.  At [line 191](https://github.com/Devolutions/slauth/blob/master/src/webauthn/server/mod.rs#L191), if the if the context does not contain an RP ID, the origin is used.  However, according to the [WebAuthn spec](https://w3c.github.io/webauthn/#rp-id), the default RP ID is the hostname of the origin without the scheme and port number.  From the spec:

> For example, given a Relying Party whose origin is https://login.example.com:1337, then the following
> RP IDs are valid: `login.example.com` (default) and `example.com`, but not `m.login.example.com` and not `com`.

The same may apply at [line 474](https://github.com/Devolutions/slauth/blob/master/src/webauthn/server/mod.rs#L474) too.

**Comment by LucFauvel** [comment]
Hi,

Thank you for your feedback, it could indeed cause issues if the RP ID is not set on credential creation, the work around for now would be to set an RP ID. Feel free to open a pull request if this issue impacts you directly, for now I don't think we'll have time to fix it soon. I would suggest the use of the [url crate](https://docs.rs/url/latest/url/) for this specific issue.
